### PR TITLE
Handle NPM Bundled Dependencies

### LINKED ISSUE #13: Deps.dev Dependency Resolver Fails with Packages from golang.org
```
$ git log -1 --oneline
3d11e26 (HEAD -> cedric.vanrompay/gopkg.in, origin/cedric.vanrompay/gopkg.in) test cmd/depscore with all gopkg.in formats
$ go run ./cmd/depscore --ecosystem go --package github.com/google/go-cmp --version v0.4.0
ERROR: evaluating score: evaluating aggregated trustworthiness of golang.org/x/xerrors: evaluating intrinsic trustworthiness of package: getting repository: no source repository found for package version
exit status 1
```

Similar to https://github.com/DataDog/aggregated-dependency-score/pull/12

### PR DESCRIPTION
**Pull request by cedricvanrompay-datadog**
Fixes #13 

I used a test-driven methodology: first a failing test triggering the bug we want to fix, then the fix.

I also started using a data file and a program for integration tests instead of a series of invocations in the GitHub workflow. This will scale better and can be reused for other implementations like the Python one.

### CODE REVIEW

**Comment by cedricvanrompay-datadog** [comment]
Test fails as expected:

> Run go run ./cmd/integration-tests
> ERROR: running test case "NPM package with bundled dependencies": evaluating aggregated trustworthiness of cdk8s>2.69.33>yaml: evaluating intrinsic trustworthiness of package: getting repository: no source repository found for package version
exit status 1

It was hard to find a good test case because you have packages with bundled dependencies that still work with the current version (see https://github.com/DataDog/aggregated-dependency-score/issues/17#issuecomment-2598455841) and then you have packages like `@aws-cdk/core` that fail even after the fix due to other issues, typically when they have many dependencies and one of them does not have an OSSF Scorecard available.

File: depsdotdev.go [hunk 1]
```diff
@@ -171,6 +178,70 @@ func (c *client) GetDirectDependencies(ctx context.Context, p Package) ([]Packag
...
+		if p.Ecosystem == "npm" {
+			bundledDependencies, err := c.getNPMBundledDependencies(ctx, versionKey)
+			if err != nil {
+				return nil, fmt.Errorf("getting bundled dependencies: %w", err)
+			}
+
+			result = append(result, bundledDependencies...)
+		}
+
+		// TODO log a warning if hasBundledDependencies is true and the ecosystem is NOT npm
```
Comment (juliendoutre) [inline depsdotdev.go:191]: Remaining leftover?

File: cmd/integration-tests/integration-tests.go [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+
+func run() (err error) {
+	testData := struct {
+		RealCases []testCase `json:"real_cases"`
+	}{}
+
+	testDataBytes, err := os.ReadFile("test-data.json")
+	if err != nil {
+		return fmt.Errorf("reading test data: %w", err)
+	}
```
Comment (juliendoutre) [inline cmd/integration-tests/integration-tests.go:28]: [nit] why not using go embed instead?

File: depsdotdev.go [hunk 3]
```diff
@@ -171,6 +178,70 @@ func (c *client) GetDirectDependencies(ctx context.Context, p Package) ([]Packag
 		})
 	}
 
+	if hasBundledDependencies {
+		if p.Ecosystem == "npm" {
```
Comment (juliendoutre) [inline depsdotdev.go:182]: Maybe use a string constant instead of "npm"?

**Review by juliendoutre — APPROVED** [review]

File: depsdotdev.go (hunk 1 above)
Comment (cedricvanrompay-datadog) [reply depsdotdev.go]: I still haven't implemented logging, and since this is a package and not an app it's a bit harder to do it right so I'll do it later.

I created #19 and added mentions to it in [c6144fb](https://github.com/DataDog/aggregated-dependency-score/pull/18/commits/c6144fb3d3f995ef787ace45cf6a65e69291cff5)

File: cmd/integration-tests/integration-tests.go (hunk 2 above)
Comment (cedricvanrompay-datadog) [reply cmd/integration-tests/integration-tests.go:28]: doesn't go embedding require that the file is "in the package"?

Here it's outside so that it can be reused by other implementations.

Also later this will let us use different data files if we want.

File: depsdotdev.go (hunk 3 above)
Comment (cedricvanrompay-datadog) [reply depsdotdev.go:183]: The `aggregdepscore` package is not yet declaring such constants, I think I will figure later how I want to do it.

I added a TODO comment in `[e797443](https://github.com/DataDog/aggregated-dependency-score/pull/18/commits/e79744337d73e0e23cef4850e8d882c3aece08cc)`

**Comment by cedricvanrompay-datadog** [comment]
@juliendoutre I am merging this, see my responses to your comments.
